apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-e2e
  namespace: devops-e2e
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - devops-e2e.example.com
    secretName: devops-e2e-tls
  rules:
  - host: devops-e2e.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-e2e
            port:
              number: 80